version: "3"
services:
  vwork_rails_server:
    build: .
    restart: always
    ports: 
      - "3000"
    links:
      - db
    command: bundle exec rails s
  vwork_rails_migrate:
    build: .
    restart: on-failure
    links:
      - db
    environment:
      - 'DISABLE_DATABASE_ENVIRONMENT_CHECK=1'
    command: bin/reset_and_fake.sh
  db:
    image: postgres:12
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=vwork_rails'
    shm_size: "256mb"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432"
volumes:
  pg_data: {}
