version: "3"
services:
  vwork_rails_server:
    build: .
    restart: always
    ports: 
      - "3000"
    volumes:
      - "vwork_rails_data:/vwork_rails/data"
    environment:
      - 'DISABLE_DATABASE_ENVIRONMENT_CHECK=1'
    command: bin/reset_and_server.sh
volumes:
  vwork_rails_data: {}
