Metrics:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
