source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'faker'
gem 'graphql'
gem 'graphql-errors'
gem 'jbuilder', '~> 2.5'
gem 'pg'
gem 'puma', '~> 3.12'
gem 'rails', '~> 6.0'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks', '~> 5'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  # https://github.com/ctran/annotate_models/issues/620
  gem 'annotate', git: 'https://github.com/ctran/annotate_models.git', branch: :develop
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

gem 'graphiql-rails', group: :development
